#include "customer.h"
#include "index_tree.h"


DEFINE_INDEX_CMP(CUSTOMER_ID_CMP, CUSTOMER_ID_INDEX);
DEFINE_INDEX_CMP(CUSTOMER_NAME_CMP, CUSTOMER_NAME_INDEX);
DEFINE_INDEX_CMP(CUSTOMER_TELEPHONE_CMP, CUSTOMER_TELEPHONE_INDEX);
